---
ansible_user: "cisco"
ansible_password: "Cisco123"
ansible_network_os: cisco.ios.ios
ansible_become: yes
ansible_become_method: enable
ansible_become_password: "Cisco123"
ansible_connection: network_cli
