---
default_gateway: 192.168.178.1
router_id: 192.168.0.1
loopback0: 192.168.0.1/32
interfaces:
  gigabitEthernet0/1: 
    ip: 10.0.0.2/24
    description: to_asw01
  gigabitEthernet0/2: 
    ip: 10.0.10.2/24
    description: to_asw02
  gigabitEthernet0/3: 
    ip: 10.0.20.2/24
    description: to_asw03
  gigabitEthernet0/0: 
    ip: 192.168.178.11/24
    description: to_mgmt
  gigabitEthernet1/0:
    ip: 10.100.0.1/24
    description: to_TLA
  vlan2270:
    ip: 10.155.1.4/24
    description: to_netmod
ospf:
  networks:
    - network: 10.0.0.0
      mask: 0.255.255.255
    - network: 192.168.0.0
      mask: 0.0.0.255
    - network: 192.168.178.0
      mask: 0.0.0.255
    - network: 10.100.0.0
      mask: 0.0.0.255
