---
default_gateway: 192.168.178.1
router_id: 192.168.0.3
loopback0: 192.168.0.3/32
interfaces:
  gigabitEthernet0/1: 
    ip: 10.0.0.1/24
    description: to_csw01
  gigabitEthernet0/2:
    ip: 10.10.0.1/24
    description: to_csw02
  gigabitEthernet0/0: 
    ip: 192.168.178.13/24
    description: to_mgmt
  vlan2270:
    ip: 10.155.1.1/24
    description: to_netmod
ospf:
  networks:
    - network: 10.0.0.0
      mask: 0.255.255.255
    - network: 192.168.0.0
      mask: 0.0.0.255
    - network: 192.168.178.0
      mask: 0.0.0.255
